//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileModel
    {
        public int MobileID { get; set; }
        public string Model { get; set; }
        public string Brand { get; set; }
        public string Amount { get; set; }
        public string Picture { get; set; }
    }
}
